/**
 * TuitionStore - Supabase Storage engine for Tuition Payment Web App
 * Persists student details, tuition amounts, payment status, and uploaded PNG slips to the cloud.
 */

const SUPABASE_URL = 'https://pshkcdjluvgtuawqumio.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzaGtjZGpsdXZndHVhd3F1bWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3NDk4OTYsImV4cCI6MjA5NTMyNTg5Nn0.xOizPzboTNtAEYYfdoR1qhMV58USapPUxgcKjMo4Naw';

class TuitionStore {
    constructor() {
        // Initialize Supabase client
        this.supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    }

    /**
     * Initialize the database and seed data if empty
     */
    async init() {
        try {
            await this.seedDataIfEmpty();
            return true;
        } catch (err) {
            console.error("Failed to initialize or seed Supabase database", err);
            return true; // Still resolve so the app loads (it will show empty states if tables missing)
        }
    }

    // --- STUDENT OPERATIONS ---

    async getStudents() {
        const { data, error } = await this.supabase
            .from('students')
            .select('*');
        if (error) throw error;
        return data || [];
    }

    async getStudentById(id) {
        const { data, error } = await this.supabase
            .from('students')
            .select('*')
            .eq('id', id)
            .single();
        
        // Supabase returns an error for single() if 0 rows are found, which is annoying. Let's catch it.
        if (error && error.code === 'PGRST116') return null; 
        if (error) throw error;
        return data;
    }

    async addStudent(student) {
        const { data, error } = await this.supabase
            .from('students')
            .insert([student])
            .select()
            .single();
        if (error) throw error;
        return data;
    }

    async updateStudent(student) {
        const { id, ...updateData } = student;
        const { data, error } = await this.supabase
            .from('students')
            .update(updateData)
            .eq('id', id)
            .select()
            .single();
        if (error) throw error;
        return data || student;
    }

    async deleteStudent(id) {
        const { error } = await this.supabase
            .from('students')
            .delete()
            .eq('id', id);
        if (error) throw error;
        return true;
    }

    // --- PAYMENT OPERATIONS ---

    async getPayments() {
        const { data, error } = await this.supabase
            .from('payments')
            .select('*');
        if (error) throw error;
        return data || [];
    }

    async getPaymentsByStudentId(studentId) {
        const { data, error } = await this.supabase
            .from('payments')
            .select('*')
            .eq('studentId', studentId)
            .order('dateTime', { ascending: false });
        if (error) throw error;
        return data || [];
    }

    async addPayment(payment) {
        // ID is auto-generated by Supabase, remove it if it exists (e.g. from mock data)
        const { id, ...insertData } = payment;
        const { data, error } = await this.supabase
            .from('payments')
            .insert([insertData])
            .select()
            .single();
        if (error) throw error;
        return data;
    }

    async updatePayment(payment) {
        const { id, ...updateData } = payment;
        const { data, error } = await this.supabase
            .from('payments')
            .update(updateData)
            .eq('id', id)
            .select()
            .single();
        if (error) throw error;
        return data || payment;
    }

    async getPaymentById(id) {
        const { data, error } = await this.supabase
            .from('payments')
            .select('*')
            .eq('id', id)
            .single();
        if (error && error.code === 'PGRST116') return null;
        if (error) throw error;
        return data;
    }

    // --- SEED MOCK DATA ---

    async seedDataIfEmpty() {
        // Try to fetch students to see if table exists and is empty
        let students = [];
        try {
            students = await this.getStudents();
        } catch (e) {
            console.error("Supabase table might not exist yet. Please run the SQL script.");
            return;
        }

        if (students.length > 0) {
            return; // Database already seeded
        }

        console.log("Database empty. Seeding tuition payment mock data to Supabase...");

        // 1. Create Mock Student list
        const mockStudents = [
            { id: "STD001", name: "สมชาย ใจดี", room: "1", year: "1", totalTuition: 60000, paidAmount: 60000, status: "paid" },
            { id: "STD002", name: "สมหญิง รักเรียน", room: "2", year: "1", totalTuition: 60000, paidAmount: 20000, status: "installment" },
            { id: "STD003", name: "เกรียงไกร มุ่งมั่น", room: "1", year: "2", totalTuition: 60000, paidAmount: 0, status: "pending" },
            { id: "STD004", name: "พลอยใส รักดี", room: "3", year: "1", totalTuition: 60000, paidAmount: 0, status: "rejected" },
            { id: "STD005", name: "อนันต์ ยอดเยี่ยม", room: "2", year: "2", totalTuition: 60000, paidAmount: 0, status: "unpaid" }
        ];

        for (const student of mockStudents) {
            await this.addStudent(student);
        }

        // Generate beautiful base64 mock slips to populate database
        const mockSlips = {
            approved: this.generateMockSlipBase64("STD001", "สมชาย ใจดี", 60000, "15/05/2026 10:30"),
            installment: this.generateMockSlipBase64("STD002", "สมหญิง รักเรียน", 20000, "12/05/2026 14:15"),
            pending: this.generateMockSlipBase64("STD003", "เกรียงไกร มุ่งมั่น", 20000, "16/05/2026 09:45"),
            rejected: this.generateMockSlipBase64("STD004", "พลอยใส รักดี", 10000, "08/05/2026 16:20")
        };

        // 2. Create Mock Payments history
        const mockPayments = [
            // STD001: Paid in Full, Approved
            {
                studentId: "STD001",
                amount: 60000,
                dateTime: "2026-05-15T10:30:00",
                slipImage: mockSlips.approved,
                slipName: "slip_STD001_1715769000.png",
                status: "approved",
                refNo: "SCB2026051590812",
                verificationDate: "2026-05-15T11:00:00",
                comment: "ยอดชำระเต็มจำนวน ได้รับเอกสารครบถ้วน"
            },
            // STD002: Installment 1, Approved
            {
                studentId: "STD002",
                amount: 20000,
                dateTime: "2026-05-12T14:15:00",
                slipImage: mockSlips.installment,
                slipName: "slip_STD002_1715523300.png",
                status: "approved",
                refNo: "KBK2026051241103",
                verificationDate: "2026-05-12T15:30:00",
                comment: "ชำระงวดที่ 1/3 ผ่านธนาคารกสิกรไทย"
            },
            // STD003: Installment 1, Pending Verification
            {
                studentId: "STD003",
                amount: 20000,
                dateTime: "2026-05-16T09:45:00",
                slipImage: mockSlips.pending,
                slipName: "slip_STD003_1715852700.png",
                status: "pending",
                refNo: "BAY2026051670982",
                verificationDate: null,
                comment: ""
            },
            // STD004: Payment Rejected
            {
                studentId: "STD004",
                amount: 10000,
                dateTime: "2026-05-08T16:20:00",
                slipImage: mockSlips.rejected,
                slipName: "slip_STD004_1715181600.png",
                status: "rejected",
                refNo: "BBL2026050853489",
                verificationDate: "2026-05-09T09:00:00",
                comment: "จำนวนเงินในสลิปไม่ถูกต้อง (ระบุชำระ 20,000 แต่ยอดโอนจริงคือ 10,000) กรุณาทำรายการใหม่"
            }
        ];

        for (const payment of mockPayments) {
            await this.addPayment(payment);
        }

        console.log("Tuition Supabase Database Seeded successfully with mock PNG slips!");
    }

    /**
     * Utility method to generate a premium-looking base64 E-Slip image
     * rendered programmatically on a Canvas! This eliminates placeholder files and
     * creates an extremely authentic, beautiful demonstration!
     */
    generateMockSlipBase64(stdId, stdName, amount, dateStr, phoneStr) {
        const canvas = document.createElement('canvas');
        canvas.width = 460;
        canvas.height = 620;
        const ctx = canvas.getContext('2d');

        // Defaults
        const nameVal = stdName || 'วิริวัลย์ เปสุยะ รุ่น21';
        const idVal = stdId || 'รหัส0338';
        const phoneVal = phoneStr || '0811322816';
        const amountVal = amount ? parseFloat(amount) : 2500;
        const dateVal = dateStr || '22 มี.ค. 69 10:31 น.';

        // 1. Background (Light Blue-Green Gradient matching Kasikornbank K+ Slip)
        const bgGrad = ctx.createLinearGradient(0, 0, 0, canvas.height);
        bgGrad.addColorStop(0, '#e5f6f7');
        bgGrad.addColorStop(0.3, '#f2fafb');
        bgGrad.addColorStop(1, '#ffffff');
        ctx.fillStyle = bgGrad;
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        // 2. Draw Decorative Money Float Shapes on Background
        ctx.fillStyle = 'rgba(16, 185, 129, 0.04)';
        // Rect 1
        ctx.save();
        ctx.translate(350, 60);
        ctx.rotate(Math.PI / 8);
        ctx.fillRect(0, 0, 40, 24);
        ctx.restore();
        // Rect 2
        ctx.save();
        ctx.translate(410, 100);
        ctx.rotate(-Math.PI / 12);
        ctx.fillRect(0, 0, 36, 20);
        ctx.restore();

        // 3. Header Section
        ctx.textAlign = 'left';
        // "โอนเงินสำเร็จ" Green Accent Bar
        ctx.fillStyle = '#11b880';
        ctx.fillRect(15, 20, 5, 45);

        ctx.fillStyle = '#1d1d1f';
        ctx.font = 'bold 20px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText('โอนเงินสำเร็จ', 28, 40);

        ctx.fillStyle = '#6e6e73';
        ctx.font = '12px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText(dateVal, 28, 60);

        // K+ Logo (Top Right)
        ctx.textAlign = 'right';
        ctx.fillStyle = '#1d1d1f';
        ctx.font = 'bold 28px Arial, sans-serif';
        ctx.fillText('K', 410, 50);
        ctx.fillStyle = '#11b880';
        ctx.font = 'bold 24px Arial, sans-serif';
        ctx.fillText('+', 425, 48);
        ctx.textAlign = 'left'; // Reset

        // Divider
        ctx.strokeStyle = 'rgba(0,0,0,0.06)';
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(15, 80);
        ctx.lineTo(canvas.width - 15, 80);
        ctx.stroke();

        // 4. FROM SECTION (Kasikornbank Circle Logo)
        // Red Outer Circle for Kbank Logo
        ctx.fillStyle = '#e53e3e';
        ctx.beginPath();
        ctx.arc(45, 130, 22, 0, Math.PI * 2);
        ctx.fill();

        // Stylized Rice sheaf logo inside circle (KBank icon representation)
        ctx.strokeStyle = '#ffffff';
        ctx.lineWidth = 2.5;
        ctx.lineCap = 'round';
        ctx.beginPath();
        ctx.moveTo(40, 120);
        ctx.lineTo(40, 140);
        ctx.moveTo(45, 118);
        ctx.lineTo(45, 142);
        ctx.moveTo(50, 120);
        ctx.lineTo(50, 140);
        ctx.stroke();

        // From text
        ctx.fillStyle = '#1d1d1f';
        ctx.font = 'bold 13px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText(nameVal, 80, 120);
        
        ctx.font = '12px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillStyle = '#4a5568';
        ctx.fillText(`ธ.กสิกรไทย   ${phoneVal ? 'รหัส ' + idVal : idVal}`, 80, 138);
        
        ctx.fillStyle = '#718096';
        ctx.font = '11px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText(phoneVal ? `เบอร์มือถือ: ${phoneVal}` : 'xxx-x-x2215-x', 80, 154);

        // 5. CONNECTING ARROW
        ctx.strokeStyle = '#a0aec0';
        ctx.lineWidth = 1.5;
        ctx.beginPath();
        ctx.moveTo(45, 162);
        ctx.lineTo(45, 182);
        ctx.moveTo(41, 176);
        ctx.lineTo(45, 182);
        ctx.lineTo(49, 176);
        ctx.stroke();

        // 6. TO SECTION (Krungthai Bank Blue Logo)
        ctx.fillStyle = '#00a2e5';
        ctx.beginPath();
        ctx.arc(45, 215, 22, 0, Math.PI * 2);
        ctx.fill();

        // Bird symbol inside circle (KTB representation)
        ctx.fillStyle = '#ffffff';
        ctx.beginPath();
        ctx.arc(45, 215, 8, 0, Math.PI * 2);
        ctx.fill();

        // To text
        ctx.fillStyle = '#1d1d1f';
        ctx.font = 'bold 13px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText('วิทยาลัยเทคโนโลยียานยนต์', 80, 206);
        
        ctx.font = '12px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillStyle = '#4a5568';
        ctx.fillText('ธ.กรุงไทย', 80, 224);
        
        ctx.fillStyle = '#718096';
        ctx.font = '11px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText('xxx-x-x3605-x', 80, 240);

        // Divider
        ctx.strokeStyle = 'rgba(0,0,0,0.06)';
        ctx.beginPath();
        ctx.moveTo(15, 260);
        ctx.lineTo(canvas.width - 15, 260);
        ctx.stroke();

        // 7. TRANSACTION DETAILS GRID (Left Column details, Right Column QR/Barcode)
        // Draw Left Details
        ctx.fillStyle = '#718096';
        ctx.font = '12px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText('เลขที่รายการ:', 30, 290);
        
        ctx.fillStyle = '#2d3748';
        ctx.font = 'bold 13px Arial, sans-serif';
        ctx.fillText(`01${idVal.replace(/\D/g,'') || '081'}${Math.floor(Math.random()*10000)}COR${Math.floor(Math.random()*100000)}`, 30, 310);

        ctx.fillStyle = '#718096';
        ctx.font = '12px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText('จำนวนเงิน:', 30, 345);
        
        ctx.fillStyle = '#1d1d1f';
        ctx.font = 'bold 16px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText(`${amountVal.toLocaleString('th-TH', {minimumFractionDigits: 2})} บาท`, 30, 368);

        ctx.fillStyle = '#718096';
        ctx.font = '12px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText('ค่าธรรมเนียม:', 30, 405);
        
        ctx.fillStyle = '#2d3748';
        ctx.font = '12px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText('0.00 บาท', 30, 425);

        // Draw Right Barcode/QR Mockup (matching user screenshot)
        const qrX = 290;
        const qrY = 280;
        const qrSize = 120;

        // QR Box border
        ctx.strokeStyle = '#cbd5e0';
        ctx.lineWidth = 1;
        ctx.strokeRect(qrX, qrY, qrSize, qrSize);

        // QR Corners (Programmatic representation)
        ctx.fillStyle = '#1a202c';
        ctx.fillRect(qrX + 8, qrY + 8, 28, 28);
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(qrX + 14, qrY + 14, 16, 16);
        ctx.fillStyle = '#1a202c';
        ctx.fillRect(qrX + 18, qrY + 18, 8, 8);

        ctx.fillStyle = '#1a202c';
        ctx.fillRect(qrX + qrSize - 36, qrY + 8, 28, 28);
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(qrX + qrSize - 30, qrY + 14, 16, 16);
        ctx.fillStyle = '#1a202c';
        ctx.fillRect(qrX + qrSize - 26, qrY + 18, 8, 8);

        ctx.fillStyle = '#1a202c';
        ctx.fillRect(qrX + 8, qrY + qrSize - 36, 28, 28);
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(qrX + 14, qrY + qrSize - 30, 16, 16);
        ctx.fillStyle = '#1a202c';
        ctx.fillRect(qrX + 18, qrY + qrSize - 26, 8, 8);

        // Mock QR Noise (Small Squares)
        ctx.fillStyle = '#2d3748';
        for (let i = 0; i < 18; i++) {
            const rx = qrX + 38 + Math.floor(Math.random() * 40);
            const ry = qrY + 8 + Math.floor(Math.random() * 100);
            ctx.fillRect(rx, ry, 6, 6);
        }
        for (let i = 0; i < 10; i++) {
            const rx = qrX + 8 + Math.floor(Math.random() * 100);
            const ry = qrY + 38 + Math.floor(Math.random() * 40);
            ctx.fillRect(rx, ry, 6, 6);
        }

        // Label under QR Code
        ctx.fillStyle = '#718096';
        ctx.font = '10px "Noto Sans Thai", Arial, sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText('สแกนตรวจสอบสลิป', qrX + qrSize / 2, qrY + qrSize + 16);
        ctx.textAlign = 'left'; // Reset

        // Divider
        ctx.strokeStyle = 'rgba(0,0,0,0.06)';
        ctx.beginPath();
        ctx.moveTo(15, 460);
        ctx.lineTo(canvas.width - 15, 460);
        ctx.stroke();

        // 8. Bottom Note Section
        ctx.fillStyle = '#4a5568';
        ctx.font = 'bold 12px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillText(`บันทึกช่วยจำ: ${nameVal} ${idVal}`, 30, 490);

        // Green Safe Stamp Banner
        ctx.fillStyle = '#f0fdf4';
        ctx.fillRect(0, 530, canvas.width, 90);
        
        ctx.fillStyle = '#15803d';
        ctx.font = 'bold 11px "Noto Sans Thai", Arial, sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText('หลักฐานการโอนเงินสำเร็จด้วยแอป K PLUS ของผู้โอน', canvas.width / 2, 560);
        ctx.font = '10px "Noto Sans Thai", Arial, sans-serif';
        ctx.fillStyle = '#16a34a';
        ctx.fillText('ข้อมูลการโอนเงินส่งไปยังสถาบันวิทยาลัยเทคโนโลยียานยนต์สำเร็จ', canvas.width / 2, 580);

        // Security side thin lines
        ctx.strokeStyle = '#11b880';
        ctx.lineWidth = 4;
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.lineTo(0, canvas.height);
        ctx.moveTo(canvas.width, 0);
        ctx.lineTo(canvas.width, canvas.height);
        ctx.stroke();

        return canvas.toDataURL('image/png');
    }
}

// Global instance
window.tuitionStore = new TuitionStore();
